//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugSquisher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BugSquisher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to damn
        ///damned
        ///damnable
        ///damnation
        ///damnit
        ///dammit
        ///bum
        ///
        ///anus
        ///arse
        ///arsehole
        ///ass
        ///ass-hat
        ///ass-pirate
        ///assbag
        ///assbandit
        ///assbanger
        ///assbite
        ///assclown
        ///asscock
        ///asscracker
        ///asses
        ///assface
        ///assfuck
        ///assfucker
        ///assgoblin
        ///asshat
        ///asshead
        ///asshole
        ///asshopper
        ///assjacker
        ///asslick
        ///asslicker
        ///assmonkey
        ///assmunch
        ///assmuncher
        ///assnigger
        ///asspirate
        ///assshit
        ///assshole
        ///asssucker
        ///asswad
        ///asswipe
        ///bampot
        ///bastard
        ///beaner
        ///bitch
        ///bitchass
        ///bitches
        ///bitchtits
        ///bitchy
        ///blow job
        ///blowjob
        ///bollocks
        ///bollox
        ///boner
        ///broth [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REALLY_BAD_WORDS___DO_NOT_READ_THIS {
            get {
                return ResourceManager.GetString("REALLY_BAD_WORDS___DO_NOT_READ_THIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I
        ///a
        ///ad
        ///ah
        ///am
        ///an
        ///as
        ///at
        ///by
        ///do
        ///eh
        ///er
        ///go
        ///ha
        ///hi
        ///ho
        ///id
        ///if
        ///in
        ///is
        ///it
        ///me
        ///my
        ///no
        ///of
        ///oh
        ///ok
        ///on
        ///or
        ///ox
        ///pi
        ///so
        ///to
        ///uh
        ///up
        ///us
        ///we
        ///abe
        ///ace
        ///act
        ///add
        ///ado
        ///aft
        ///age
        ///ago
        ///aha
        ///aid
        ///ail
        ///aim
        ///air
        ///alb
        ///ale
        ///ali
        ///all
        ///alm
        ///alp
        ///alt
        ///ama
        ///ami
        ///amp
        ///amt
        ///amu
        ///amy
        ///ana
        ///and
        ///ani
        ///ann
        ///ant
        ///any
        ///ape
        ///apo
        ///apt
        ///arc
        ///are
        ///ark
        ///arm
        ///art
        ///ash
        ///ask
        ///asp
        ///ass
        ///ate
        ///aug
        ///auk
        ///aut
        ///ave
        ///awe
        ///awl
        ///awn
        ///axe
        ///aye
        ///baa
        ///bad
        ///bag
        ///bah
        ///ban
        ///bar
        ///bas
        ///bat
        ///bay
        ///bed
        ///bee
        ///beg
        ///ben
        ///bet
        ///bey
        ///bib
        ///bid
        ///big
        ///bin
        ///bio
        ///bit
        ///boa
        ///bob
        ///bog
        ///bon
        ///boo
        ///bop
        ///bow
        ///box
        ///boy
        ///bra
        ///bro
        ///bud
        ///bug
        ///bum
        ///bun
        ///bur
        ///bus
        ///but
        ///buy
        ///bye
        ///byu
        ///cab
        ///cad
        ///cam
        ///can
        ///cap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string US_DICTIONARY {
            get {
                return ResourceManager.GetString("US_DICTIONARY", resourceCulture);
            }
        }
    }
}
